export const CONTRACT_CATEGORIES = [
  { id: "work", label: "근로·고용" },
  { id: "freelance", label: "프리랜서·용역" },
  { id: "realestate", label: "부동산·임대차" },
  { id: "business", label: "사업·동업" },
  { id: "investment", label: "투자·주식" },
  { id: "ip", label: "지식재산권" },
  { id: "trade", label: "매매·거래" },
  { id: "settlement", label: "합의서" },
  { id: "certified", label: "내용증명" },
];

export const CONTRACT_LIST = [
  // 근로·고용
  { id: "labor-flex-5up", label: "근로계약서(유연근무, 5인 이상)", category: "work" },
  { id: "labor-flex-5dn", label: "근로계약서(유연근무, 5인 미만)", category: "work" },
  { id: "labor-15up-5up", label: "근로계약서(주15시간이상, 5인이상)", category: "work" },
  { id: "labor-15up-5dn", label: "근로계약서(주15시간이상, 5인 미만)", category: "work" },
  { id: "labor-15dn-5up", label: "근로계약서(주15시간미만, 5인이상)", category: "work" },
  { id: "labor-15dn-5dn", label: "근로계약서(주15시간미만, 5인미만)", category: "work" },
  { id: "labor-change-5up", label: "근로계약서(근로조건 변경용, 5인 이상)", category: "work" },
  { id: "labor-change-5dn", label: "근로계약서(근로조건 변경용, 5인 미만)", category: "work" },
  { id: "labor-salary-5up", label: "근로계약서(연봉갱신용, 5인 이상)", category: "work" },
  { id: "labor-salary-5dn", label: "근로계약서(연봉갱신용, 5인 미만)", category: "work" },
  { id: "labor-daily", label: "근로계약서(일용근로자)", category: "work" },
  { id: "labor-copy", label: "근로계약서 교부 확인서", category: "work" },
  { id: "employment-agreement", label: "입사자서약서", category: "work" },
  { id: "executive-contract", label: "임원계약서", category: "work" },
  { id: "resignation-general", label: "퇴사자서약서(일반용)", category: "work" },
  { id: "resignation-recommend", label: "퇴사자서약서(권고사직용)", category: "work" },
  // 프리랜서·용역
  { id: "service-general", label: "용역계약서(일반)", category: "freelance" },
  { id: "service-it", label: "용역계약서(IT 및 소프트웨어·정보화사업)", category: "freelance" },
  { id: "service-construction", label: "용역계약서(건설 및 기타 공사)", category: "freelance" },
  { id: "service-ad", label: "용역계약서(광고 및 홍보대행)", category: "freelance" },
  { id: "service-research", label: "용역계약서(조사 및 학술연구)", category: "freelance" },
  { id: "housekeeper", label: "가사도우미계약서", category: "freelance" },
  { id: "childcare", label: "육아도우미계약서", category: "freelance" },
  { id: "freelancer", label: "프리랜서 계약서", category: "freelance" },
  { id: "freelancer-delivery", label: "프리랜서 계약서(배달 종사자용)", category: "freelance" },
  { id: "sns-marketing", label: "SNS 홍보대행업무 계약서", category: "freelance" },
  { id: "event-agency", label: "이벤트 대행 업무 계약서", category: "freelance" },
  { id: "review-agreement", label: "리뷰 약정서", category: "freelance" },
  { id: "advisory", label: "자문(고문)계약서", category: "freelance" },
  { id: "subcontract", label: "도급계약서", category: "freelance" },
  { id: "creator-mcn", label: "크리에이터 전속 계약서(MCN)", category: "freelance" },
  // 부동산·임대차
  { id: "realestate-direct",  label: "부동산 임대차 계약서(직거래용)",    category: "realestate" },
  { id: "startup-lease",      label: "입주계약서(창업지원단용)",          category: "realestate" },
  { id: "sharehouse-landlord",label: "하우스 셰어계약서(집주인용)",        category: "realestate" },
  { id: "sharehouse-tenant",  label: "하우스 셰어계약서(세입자용)",        category: "realestate" },
  { id: "commercial-lease",   label: "상가임대차계약서",                   category: "realestate" },
  { id: "commercial-premium", label: "상가건물 임대차 권리금계약서",        category: "realestate" },
  { id: "realestate-lease",   label: "임대차 계약서 주의사항",             category: "realestate" },
  { id: "realestate-sale",    label: "부동산 매매 계약서 주의사항",         category: "realestate" },
  { id: "realestate-permit",  label: "토지거래허가구역 거래 필요 서류",     category: "realestate" },
  // 사업·동업
  { id: "joint-venture", label: "공동사업약정서", category: "business" },
  { id: "partnership-no-corp", label: "동업계약서(법인 미설립)", category: "business" },
  { id: "partnership-stock", label: "동업계약서(주식회사 설립 예정)", category: "business" },
  { id: "partnership-3plus", label: "동업계약서(3인 이상)", category: "business" },
  { id: "partnership-dissolve", label: "동업해지계약서", category: "business" },
  { id: "mou", label: "업무협약서", category: "business" },
  { id: "biz-transfer", label: "영업양수도 계약서", category: "business" },
  { id: "nda", label: "NDA(비밀유지계약서)", category: "business" },
  // 투자·주식
  { id: "investor-union", label: "개인투자조합 표준규약", category: "investment" },
  { id: "common-stock", label: "보통주 투자계약서", category: "investment" },
  { id: "vc-standard", label: "투자계약서(VC표준계약서)", category: "investment" },
  { id: "redeemable-preferred", label: "투자계약서(상환전환우선주)", category: "investment" },
  { id: "shareholder-2", label: "주주간계약서", category: "investment" },
  { id: "shareholder-3plus", label: "주주간계약서(3인이상)", category: "investment" },
  { id: "stock-transfer-condition", label: "주식양수도계약서(정지조건부)", category: "investment" },
  { id: "stock-transfer", label: "주식양수도계약서", category: "investment" },
  { id: "stock-option-general", label: "스톡옵션계약서(주식매수선택권부여계약서 일반)", category: "investment" },
  { id: "stock-option-vesting", label: "스톡옵션계약서(베스팅조항포함)", category: "investment" },
  // 지식재산권
  { id: "patent-license", label: "특허권 실시계약서", category: "ip" },
  { id: "trademark-license", label: "상표권 사용계약서", category: "ip" },
  { id: "copyright-exclusive", label: "저작권 전용계약서", category: "ip" },
  { id: "copyright-transfer", label: "저작권 양수도 계약서", category: "ip" },
  { id: "ip-transfer", label: "양수도계약서(지식재산권)", category: "ip" },
  { id: "tech-transfer", label: "기술 이전계약서", category: "ip" },
  { id: "portrait-license", label: "초상권 사용계약서", category: "ip" },
  // 매매·거래
  { id: "movable-sale", label: "매매계약서(동산)", category: "trade" },
  { id: "movable-ip-sale", label: "매매계약서(동산, 지식재산권)", category: "trade" },
  { id: "supply", label: "물품공급계약서", category: "trade" },
  { id: "exclusive-supply", label: "독점물품공급계약서", category: "trade" },
  { id: "exclusive-sales", label: "독점물품판매계약서", category: "trade" },
  { id: "agency-sales", label: "대리점 물품판매계약서", category: "trade" },
  { id: "consignment-sales", label: "위수탁판매계약서", category: "trade" },
  { id: "used-trade", label: "중고거래 약정서", category: "trade" },
  { id: "debt-transfer", label: "채권양수도계약서", category: "ip" },
  { id: "debt-pledge", label: "채권질권설정계약서", category: "ip" },
  { id: "collateral", label: "양도담보설정계약서", category: "ip" },
  { id: "debt-assumption", label: "채무인수계약서", category: "ip" },
  { id: "advance-payment", label: "가지급금 약정서", category: "trade" },
  { id: "loan-small", label: "금전소비대차계약서(소액용)", category: "trade" },
  { id: "loan-large", label: "금전소비대차계약서(고액용)", category: "trade" },
  // 합의서
  { id: "accident-civil", label: "교통사고 합의서(민사)", category: "settlement" },
  { id: "accident-criminal", label: "교통사고 합의서(형사)", category: "settlement" },
  { id: "accident-minor", label: "교통사고 합의서(경미한 사고용)", category: "settlement" },
  { id: "assault", label: "합의서(폭행)", category: "settlement" },
  { id: "defamation", label: "합의서(명예훼손)", category: "settlement" },
  { id: "divorce", label: "이혼 합의서", category: "settlement" },
  { id: "contract-cancel", label: "계약 해제(해지) 합의서", category: "settlement" },
  { id: "money-dispute", label: "합의서(금전분쟁)", category: "settlement" },
  { id: "settlement-other", label: "합의서(기타)", category: "settlement" },
  // 내용증명
  { id: "cert-deposit-return", label: "내용증명(보증금 반환 청구)", category: "certified" },
  { id: "cert-defect", label: "내용증명(하자보수청구-임차인용)", category: "certified" },
  { id: "cert-cancel-tenant", label: "내용증명(부동산 계약해지-세입자용)", category: "certified" },
  { id: "cert-cancel-landlord", label: "내용증명(부동산 계약해지-임대인용)", category: "certified" },
  { id: "cert-noise", label: "내용증명(층간소음)", category: "certified" },
  { id: "cert-rent-claim", label: "내용증명(월세 청구)", category: "certified" },
  { id: "cert-rent-evict", label: "내용증명(임대료 연체로 인한 계약 해지 및 명도 청구)", category: "certified" },
  { id: "cert-premium-damage", label: "내용증명(권리금 손해배상)", category: "certified" },
  { id: "cert-lease-extend-no", label: "내용증명(임대차 계약연장 불허통지)", category: "certified" },
  { id: "cert-commercial-extend-no", label: "내용증명(상가임대차 계약연장 불허통지)", category: "certified" },
  { id: "cert-property-damage", label: "내용증명(물건, 권리침해 손해배상 등)", category: "certified" },
  { id: "cert-body-damage", label: "내용증명(신체침해 손해배상 등)", category: "certified" },
  { id: "cert-contract-cancel-notice", label: "내용증명(계약해지 통지)", category: "certified" },
  { id: "cert-contract-cancel-reply", label: "내용증명(계약해지 통지 답변서)", category: "certified" },
  { id: "cert-contract-perform", label: "내용증명(계약이행 청구)", category: "certified" },
  { id: "cert-rights-claim", label: "내용증명(권리청구)", category: "certified" },
  { id: "cert-unjust-return", label: "내용증명(부당이득 반환)", category: "certified" },
  { id: "cert-investment-return", label: "내용증명(투자금 반환)", category: "certified" },
  { id: "cert-breakup-settle", label: "내용증명(파혼, 이별시 선물 반환 등 정산 요청)", category: "certified" },
  { id: "cert-service-fee", label: "내용증명(용역대금 청구)", category: "certified" },
  { id: "cert-service-return", label: "내용증명(용역대금 반환 청구)", category: "certified" },
  { id: "cert-sale-fee", label: "내용증명(매매대금 청구용)", category: "certified" },
  { id: "cert-sale-fee-reply", label: "내용증명(매매대금 청구 답변서)", category: "certified" },
  { id: "cert-sale-return", label: "내용증명(매매대금 반환 청구)", category: "certified" },
  { id: "cert-wage", label: "내용증명(임금청구)", category: "certified" },
  { id: "cert-loan-claim", label: "내용증명(대여금 청구용)", category: "certified" },
  { id: "cert-loan-reply", label: "내용증명(대여금 청구 답변서)", category: "certified" },
  { id: "cert-defame-stop", label: "내용증명(명예훼손 금지)", category: "certified" },
  { id: "cert-defame-stop-reply", label: "내용증명(명예훼손 금지 답변서)", category: "certified" },
  { id: "cert-defame-cease", label: "내용증명(모욕, 명예훼손 중단청구)", category: "certified" },
  { id: "cert-ip-infringement", label: "내용증명(지식재산권 침해 중단 및 손해배상 청구)", category: "certified" },
  { id: "cert-court-notice", label: "내용증명(법원 판결, 결정 등 불이행에 대한 조치 통보)", category: "certified" },
  { id: "cert-no-debt", label: "내용증명(차용, 임대차 등 계약 관련 금전 채무 부존재 통보)", category: "certified" },
  { id: "cert-debt-transfer", label: "내용증명(양수인의 채권양도통지)", category: "certified" },
  { id: "cert-pledge", label: "내용증명(질권설정)", category: "certified" },
];

export const CONTRACTS = [
  {
    id: "labor",
    label: "근로계약서",
    icon: "💼",
    tag: "직장·알바",
    tagColor: "blue",
    summary: "알바·직장 계약 시 꼭 확인해야 할 조항",
    checklist: [
      { level: "danger", title: "임금 미기재", desc: "시급/월급 금액이 명시되지 않은 계약서는 효력 분쟁 발생 가능. 숫자로 정확히 기재되어야 합니다." },
      { level: "danger", title: "주휴수당 누락", desc: "주 15시간 이상 근무 시 주휴수당은 법적 의무입니다. '주휴수당 미지급' 조항이 있으면 무효이며 청구 가능합니다." },
      { level: "danger", title: "근무 시간·요일 미기재", desc: "근무 시간과 요일이 명시되지 않으면 사용자 임의로 변경될 수 있습니다. 구체적으로 기재 요구하세요." },
      { level: "warn", title: "포괄임금제 조항", desc: "야근·연장근로 수당을 월급에 포함시키는 방식. 실제 연장근무 시간이 많다면 불리할 수 있습니다." },
      { level: "warn", title: "수습기간 임금 삭감", desc: "수습기간 임금을 최저임금의 90% 미만으로 설정하는 것은 불법입니다. (단, 1년 이상 계약·해당 직종 제외)" },
      { level: "warn", title: "퇴직금 포기 조항", desc: "1년 이상 근무 시 퇴직금은 법적 권리. '퇴직금 없음' 조항은 무효입니다." },
      { level: "info", title: "계약 기간 확인", desc: "기간제 계약서라면 기간이 명시되어야 합니다. 2년 초과 반복 계약 시 무기계약 전환 요구 가능합니다." },
      { level: "info", title: "4대보험 가입 여부", desc: "주 15시간 이상, 월 60시간 이상 근무 시 4대보험 가입 의무입니다. 미가입 사업주는 과태료 대상입니다." },
    ],
    tips: [
      "계약서는 반드시 2부 작성해서 1부는 본인이 보관하세요.",
      "구두 약속은 증거가 되지 않습니다. 모든 조건을 서면으로 받으세요.",
      "계약서 서명 전 충분히 읽을 시간을 요구할 권리가 있습니다.",
    ],
    link: "https://www.moel.go.kr/",
    linkLabel: "고용노동부 표준계약서 다운로드",
  },
  {
    id: "lease",
    label: "임대차 계약서",
    icon: "🏠",
    tag: "부동산",
    tagColor: "green",
    summary: "전세·월세 계약 시 전세사기 예방 체크리스트",
    checklist: [
      { level: "danger", title: "등기부등본 미확인", desc: "계약 전 반드시 등기부등본을 열람하세요. 근저당·가압류·가처분이 많으면 보증금 반환 위험이 있습니다." },
      { level: "danger", title: "집주인 신원 불일치", desc: "계약자와 등기부상 소유자가 일치하는지 확인하세요. 다르다면 위임장·인감증명서를 반드시 요구하세요." },
      { level: "danger", title: "전입신고·확정일자 미취득", desc: "입주 즉시 전입신고 후 확정일자를 받아야 보증금 보호를 받을 수 있습니다." },
      { level: "danger", title: "근저당 설정 과다", desc: "근저당 채권최고액 + 보증금이 집값의 70%를 넘으면 경매 시 보증금 회수가 어렵습니다." },
      { level: "warn", title: "특약사항 독소조항", desc: "'퇴거 시 원상복구 전액 부담', '중도 해지 위약금 과다' 등의 조항은 협의 또는 삭제를 요구하세요." },
      { level: "warn", title: "전세보증보험 미가입", desc: "HUG 전세보증보험 가입을 적극 검토하세요. 보증금 반환 불능 시 HUG가 대위 지급합니다." },
      { level: "warn", title: "임대인 세금 체납 확인", desc: "국세·지방세 체납이 있으면 경매 시 세금이 먼저 배당됩니다. 납세증명서 제출을 요구하세요." },
      { level: "info", title: "계약갱신청구권 확인", desc: "2년 계약 만료 후 1회에 한해 계약갱신 요구 가능합니다. 집주인이 직접 거주가 아닌 경우 거절 불가합니다." },
    ],
    tips: [
      "계약 당일에도 등기부등본을 다시 열람하세요. 당일 근저당 설정 사례가 있습니다.",
      "전세보증보험은 입주 후 일정 기간 내 가입해야 합니다. 미루지 마세요.",
      "주택도시보증공사(HUG) 안심전세앱으로 위험도를 무료로 조회할 수 있습니다.",
    ],
    link: "https://www.khug.or.kr/",
    linkLabel: "HUG 전세보증보험 안내",
  },
  {
    id: "freelance",
    label: "프리랜서 계약서",
    icon: "💻",
    tag: "프리랜서",
    tagColor: "purple",
    summary: "외주·용역 계약 시 저작권·대금 관련 주의사항",
    checklist: [
      { level: "danger", title: "저작권 귀속 조항 확인", desc: "납품 결과물의 저작권이 '을(수급인)에게 귀속'되어야 합니다. '갑에게 모든 권리 귀속'이면 2차 활용도 불가합니다." },
      { level: "danger", title: "대금 지급 조건 미명시", desc: "지급 시기(검수 후 며칠 이내)와 방식(계좌이체)이 명확해야 합니다. 막연한 '완료 후 지급'은 분쟁 원인입니다." },
      { level: "danger", title: "범위 외 추가 작업 강요", desc: "'갑의 요청에 따른 추가 작업 무상 제공' 조항은 삭제 요구하세요. 추가 작업은 별도 계약이 원칙입니다." },
      { level: "warn", title: "무제한 수정 조항", desc: "'갑이 만족할 때까지 수정' 조항은 분쟁의 핵심입니다. 수정 횟수(예: 2회)를 명시하세요." },
      { level: "warn", title: "비밀유지 의무 과도한 범위", desc: "NDA 범위가 너무 넓으면 유사 프로젝트 수주가 어려울 수 있습니다. 범위를 구체화하세요." },
      { level: "warn", title: "지체상금 조항", desc: "납품 지연 시 과도한 위약금 조항이 있으면 협의하세요. 일반적으로 계약금의 10% 이내가 적정합니다." },
      { level: "info", title: "계약금 비율 확인", desc: "착수금(30~50%) → 중간금 → 잔금 구조가 일반적입니다. 착수금 없이 완료 후 일괄 지급은 피하세요." },
      { level: "info", title: "분쟁 해결 조항", desc: "분쟁 발생 시 관할 법원이 명시되어야 합니다. 원칙적으로 수급인 주소지 법원이 유리합니다." },
    ],
    tips: [
      "카카오톡·이메일 등 작업 지시는 모두 저장해두세요. 법적 증거가 됩니다.",
      "구두 추가 요청도 메시지로 재확인 받는 습관을 들이세요.",
      "대금 미지급 시 내용증명 발송 → 지급명령 신청 순서로 대응하세요.",
    ],
    link: "https://www.ftc.go.kr/",
    linkLabel: "공정거래위원회 표준하도급계약서",
  },
  {
    id: "employment",
    label: "취업·위촉 계약서",
    icon: "📋",
    tag: "직장·프리랜서",
    tagColor: "blue",
    summary: "정규직·계약직·위촉직 계약 시 핵심 체크",
    checklist: [
      { level: "danger", title: "경업금지 조항 범위", desc: "퇴사 후 동종업계 취업 금지 기간이 지나치게 길거나(2년 초과) 범위가 넓으면 법적 효력이 제한됩니다." },
      { level: "danger", title: "위촉 vs 근로 구분", desc: "실질적으로 지시를 받고 일하는데 '위촉' 계약이면 4대보험·퇴직금 미적용 문제가 생깁니다. 실질 판단이 중요합니다." },
      { level: "warn", title: "성과급 지급 기준 불명확", desc: "성과급 지급 기준과 시기가 구체적이지 않으면 미지급 분쟁이 발생합니다. 수치화된 기준을 요구하세요." },
      { level: "warn", title: "전직 금지 동의서", desc: "퇴사 시 별도 전직금지 동의서 서명을 요구하는 경우 범위와 기간을 꼼꼼히 확인하세요." },
      { level: "info", title: "수습기간 조건", desc: "수습기간, 평가 기준, 정규직 전환 조건이 명확히 기재되어야 합니다." },
      { level: "info", title: "복리후생 명시", desc: "식대·교통비·장비 지원 등은 계약서에 명시되어야 나중에 삭감 논쟁이 없습니다." },
    ],
    tips: [
      "위촉직이라도 실질적 근로관계라면 근로기준법 보호를 받을 수 있습니다.",
      "경업금지 조항 위반 소송은 실제로 드뭅니다. 지나치게 넓은 조항은 법원이 제한합니다.",
    ],
    link: "https://www.moel.go.kr/",
    linkLabel: "고용노동부 민원 신청",
  },
];

export const APPLICATIONS = [
  {
    id: "youth-rent",
    label: "청년 월세 지원",
    icon: "🏠",
    tag: "청년",
    tagColor: "green",
    summary: "월 최대 20만 원, 최대 12개월 지원",
    condition: "만 19~34세, 독립 거주, 소득·자산 기준 충족",
    docs: [
      { category: "신분증명", items: ["주민등록증 또는 운전면허증"] },
      { category: "주거 확인", items: ["임대차계약서 사본", "주민등록등본 (전입신고 완료 상태)"] },
      { category: "소득·자산", items: ["건강보험료 납부확인서", "소득 증빙서류 (근로소득원천징수영수증 또는 사업소득 확인서)"] },
      { category: "계좌", items: ["본인 명의 통장 사본"] },
    ],
    notes: ["부모님과 별도 거주 확인 필수 (주민등록 분리)", "월세 계약서상 임차인이 본인이어야 함", "LH 마이홈 또는 복지로에서 신청 가능"],
    link: "https://www.lh.or.kr/",
    linkLabel: "LH 마이홈 신청 바로가기",
  },
  {
    id: "policy-loan",
    label: "청년 정책대출 (버팀목·햇살론)",
    icon: "💰",
    tag: "대출",
    tagColor: "blue",
    summary: "저금리 전세·생활자금 대출",
    condition: "만 19~34세, 무주택자, 소득 기준 충족",
    docs: [
      { category: "신분 및 주거", items: ["주민등록등본", "주민등록증"] },
      { category: "주거 확인 (전세)", items: ["임대차계약서 원본", "확정일자 부여 확인서", "등기사항전부증명서 (등기부등본)"] },
      { category: "소득 증빙", items: ["근로소득: 근로소득원천징수영수증 + 재직증명서", "사업소득: 사업자등록증 + 종합소득세 신고서", "무직·구직: 고용보험 가입이력 내역서"] },
      { category: "자산 조회 동의", items: ["금융정보 조회 동의서 (은행 제공)", "건강보험료 납부확인서"] },
    ],
    notes: ["은행 방문 전 주택도시기금 포털에서 자격 조회 먼저", "전세계약 후 잔금 전에 대출 신청해야 함", "신청 은행: 우리·국민·신한·하나·농협·기업은행"],
    link: "https://nhuf.molit.go.kr/",
    linkLabel: "주택도시기금 포털 바로가기",
  },
  {
    id: "youth-savings",
    label: "청년도약계좌",
    icon: "🐣",
    tag: "청년",
    tagColor: "green",
    summary: "월 최대 70만 원 납입, 정부 기여금 최대 6%",
    condition: "만 19~34세, 개인소득 6,000만 원 이하, 가구소득 기준 충족",
    docs: [
      { category: "신분", items: ["주민등록증 또는 여권"] },
      { category: "소득 확인", items: ["근로소득원천징수영수증 (직전 과세연도)", "사업소득: 종합소득세 신고서 사본"] },
      { category: "기타", items: ["금융거래 확인서 (은행 제공)", "국세청 소득확인증명서"] },
    ],
    notes: ["취급 은행 앱에서 비대면 신청 가능 (별도 서류 최소화)", "매월 가입 신청 기간이 정해져 있음", "금융위원회 청년도약계좌 공식 채널 확인 필요"],
    link: "https://ylaccount.kinfa.or.kr/",
    linkLabel: "청년도약계좌 공식 사이트",
  },
  {
    id: "startup-loan",
    label: "청년창업사관학교 / 창업지원",
    icon: "🚀",
    tag: "창업",
    tagColor: "orange",
    summary: "창업 초기 자금 및 교육 지원",
    condition: "만 39세 이하 예비창업자 또는 창업 3년 이내",
    docs: [
      { category: "사업 계획", items: ["사업계획서 (소정 양식)", "시장 분석 자료"] },
      { category: "신분", items: ["주민등록증", "주민등록등본"] },
      { category: "사업자 (기창업)", items: ["사업자등록증명", "법인등기부등본 (법인의 경우)"] },
      { category: "기타", items: ["최종학력 증명서", "경력증명서 (해당 시)"] },
    ],
    notes: ["중소벤처기업부 K-Startup 포털에서 공고 확인", "서류 심사 → 발표 심사 단계로 진행", "지원 프로그램마다 서류 상이하므로 공고문 필수 확인"],
    link: "https://www.k-startup.go.kr/",
    linkLabel: "K-Startup 포털 바로가기",
  },
  {
    id: "health-checkup",
    label: "국가건강검진",
    icon: "🏥",
    tag: "건강",
    tagColor: "red",
    summary: "2년마다 무료 건강검진",
    condition: "건강보험 가입자 및 의료급여 수급자",
    docs: [
      { category: "필수", items: ["국민건강보험공단 건강검진표 (우편 또는 앱 확인)", "신분증"] },
      { category: "추가 (필요 시)", items: ["의사 소견서 (특정 검사 추가 요청 시)"] },
    ],
    notes: ["건강보험공단 앱에서 검진 기관 조회 및 예약 가능", "검진 당일 공복 8시간 이상 필요", "암검진은 별도 대상자 확인 필요"],
    link: "https://www.nhis.or.kr/",
    linkLabel: "국민건강보험공단 바로가기",
  },
  {
    id: "unemployment",
    label: "실업급여 신청",
    icon: "📑",
    tag: "고용",
    tagColor: "blue",
    summary: "퇴직 후 구직활동 중 급여 지원",
    condition: "비자발적 퇴직, 고용보험 180일 이상 가입",
    docs: [
      { category: "필수", items: ["이직확인서 (전 직장 발급)", "수급자격인정 신청서 (고용보험 홈페이지 작성)", "신분증"] },
      { category: "구직 활동", items: ["구직신청 확인서 (워크넷 등록 후 발급)"] },
    ],
    notes: ["퇴직 후 12개월 이내 신청 (초과 시 수급 불가)", "퇴직 다음날부터 신청 가능 / 지체 없이 신청 권장", "고용센터 방문 또는 고용24 온라인 신청 가능"],
    link: "https://www.work24.go.kr/",
    linkLabel: "고용24 실업급여 신청",
  },
];

// ── 신규 추가: 기초연금·주거급여·교육급여·아동수당 ──
APPLICATIONS.push(
  {
    id: "basic-pension",
    label: "기초연금",
    icon: "👴",
    tag: "노인",
    tagColor: "blue",
    summary: "만 65세 이상 저소득 어르신 월 최대 33만 4,810원",
    condition: "만 65세 이상, 소득인정액 단독가구 213만 원 이하 (2025년 기준)",
    docs: [
      { category: "신분·가족", items: ["신분증 (주민등록증·운전면허증·여권)", "주민등록등본 또는 가족관계증명서"] },
      { category: "금융정보", items: ["금융정보 제공 동의서 (주민센터 비치)", "본인 명의 통장 사본"] },
      { category: "소득·재산 (해당 시)", items: ["근로소득 확인서류 (급여명세서·원천징수영수증)", "임대차계약서 (임대소득 있는 경우)", "자동차등록증 (차량 소유 시)"] },
    ],
    notes: ["주소지 관할 읍·면·동 주민센터 또는 복지로 온라인 신청", "배우자가 있는 경우 부부 동반 신청 가능", "금융·부동산·자동차 자산 조회에 동의 필요"],
    link: "https://basicpension.mohw.go.kr/",
    linkLabel: "기초연금 공식 사이트",
  },
  {
    id: "housing-benefit",
    label: "주거급여",
    icon: "🏘️",
    tag: "복지",
    tagColor: "green",
    summary: "임차가구 월세 지원 또는 자가가구 집수리 지원",
    condition: "소득인정액 기준 중위소득 48% 이하 가구",
    docs: [
      { category: "신분·가족", items: ["신분증", "가족관계증명서", "주민등록등본"] },
      { category: "주거 확인 (임차가구)", items: ["임대차계약서 사본", "임대인 통장 사본 (임대료 지급 확인용)"] },
      { category: "소득·재산", items: ["소득 증빙서류 (근로소득원천징수영수증·사업소득 확인서)", "금융정보 제공 동의서", "건강보험료 납부확인서"] },
      { category: "자가가구 (수선급여 신청 시)", items: ["건물등기사항전부증명서 또는 건축물대장", "수선 필요 현황 자가 진단표 (주민센터 비치)"] },
    ],
    notes: ["읍·면·동 주민센터 또는 복지로에서 신청", "임차급여는 지역·가구원 수에 따라 상한 임차료 적용", "자가급여는 주택 노후도 평가 후 수선비 지급"],
    link: "https://www.hb.go.kr/",
    linkLabel: "주거급여 공식 사이트",
  },
  {
    id: "edu-benefit",
    label: "교육급여",
    icon: "📚",
    tag: "복지",
    tagColor: "blue",
    summary: "초·중·고 재학생 교육활동지원비 연 최대 65만 4,000원",
    condition: "기초생활수급자 또는 소득인정액 기준 중위소득 50% 이하 가구의 초·중·고 학생",
    docs: [
      { category: "가구 신분", items: ["보호자 신분증", "가족관계증명서", "주민등록등본"] },
      { category: "재학 확인", items: ["재학증명서 또는 학생증 (해당 자녀)"] },
      { category: "소득·재산", items: ["소득 증빙서류 (근로·사업·재산소득)", "금융정보 제공 동의서", "건강보험료 납부확인서"] },
    ],
    notes: ["읍·면·동 주민센터 또는 복지로 온라인 신청", "교육활동지원비는 바우처(카드) 형태로 지급", "고등학생은 교과서비·입학금·수업료 별도 지원"],
    link: "https://www.bokjiro.go.kr/",
    linkLabel: "복지로 교육급여 신청",
  },
  {
    id: "child-allowance",
    label: "아동수당",
    icon: "👶",
    tag: "아동",
    tagColor: "orange",
    summary: "만 8세 미만 아동 1인당 월 10만원 지급",
    condition: "주민등록상 국내 거주 만 8세 미만 아동 (소득·재산 무관)",
    docs: [
      { category: "필수", items: ["아동 주민등록등본", "보호자 신분증", "아동 명의 또는 보호자 명의 통장 사본"] },
      { category: "대리 신청 시", items: ["위임장", "대리인 신분증"] },
    ],
    notes: ["읍·면·동 주민센터, 복지로, 정부24 온라인 신청 가능", "출생신고와 동시에 신청하면 소급 지급 가능", "소득·재산 기준 없이 만 8세 미만 모든 아동 대상"],
    link: "https://www.childallowance.go.kr/",
    linkLabel: "아동수당 공식 사이트",
  }
);
